/* Generated By:JavaCC: Do not edit this line. linguagemConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface linguagemConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 8;
  /** RegularExpression Id. */
  int LETRAS = 9;
  /** RegularExpression Id. */
  int DIGITOS = 10;
  /** RegularExpression Id. */
  int OP_ARIT = 11;
  /** RegularExpression Id. */
  int MAIS = 12;
  /** RegularExpression Id. */
  int MENOS = 13;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 14;
  /** RegularExpression Id. */
  int DIVISAO = 15;
  /** RegularExpression Id. */
  int OP_REL = 16;
  /** RegularExpression Id. */
  int MAIOR = 17;
  /** RegularExpression Id. */
  int MENOR = 18;
  /** RegularExpression Id. */
  int IGUALDADE = 19;
  /** RegularExpression Id. */
  int DIFERENTE = 20;
  /** RegularExpression Id. */
  int IGUAL = 21;
  /** RegularExpression Id. */
  int TIPO = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int VOID = 26;
  /** RegularExpression Id. */
  int PARENTESES_A = 27;
  /** RegularExpression Id. */
  int PARENTESES_F = 28;
  /** RegularExpression Id. */
  int CHAVES_A = 29;
  /** RegularExpression Id. */
  int CHAVES_F = 30;
  /** RegularExpression Id. */
  int VIRGULA = 31;
  /** RegularExpression Id. */
  int FOR = 32;
  /** RegularExpression Id. */
  int WHILE = 33;
  /** RegularExpression Id. */
  int IF = 34;
  /** RegularExpression Id. */
  int ELSE = 35;
  /** RegularExpression Id. */
  int SWITCH = 36;
  /** RegularExpression Id. */
  int CASE = 37;
  /** RegularExpression Id. */
  int BREAK = 38;
  /** RegularExpression Id. */
  int PADRAO = 39;
  /** RegularExpression Id. */
  int PRINT = 40;
  /** RegularExpression Id. */
  int GET = 41;
  /** RegularExpression Id. */
  int MAIN = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\";\"",
    "<LETRAS>",
    "<DIGITOS>",
    "<OP_ARIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<OP_REL>",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "<TIPO>",
    "\"inteiro\"",
    "\"texto\"",
    "\"flutuante\"",
    "\"vazio\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"para\"",
    "\"enquanto\"",
    "\"se\"",
    "\"se nao\"",
    "\"switch\"",
    "\"caso\"",
    "\"sair\"",
    "\"padrao\"",
    "\"mostrar\"",
    "\"obter\"",
    "\"main\"",
    "\"_\"",
  };

}
